name: Dart CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch: # Adiciona um gatilho manual para aprovação

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
      - name: Install dependencies
        run: flutter pub get
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze project source
        run: |
          flutter analyze || true
      - name: Output Analysis Results
        if: failure()
        run: exit 1

  test:
    runs-on: ubuntu-latest
    needs: [format, analyze]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test

  security:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
      - name: Install dependencies
        run: flutter pub get

      - name: Check for outdated dependencies with Dart
        run: dart pub outdated

      - name: Scan current project
        uses: anchore/scan-action@v3
        with:
          path: "."
          fail-build: false
          output-format: table
          severity-cutoff: medium
          only-fixed: false
          add-cpes-if-none: false
          by-cve: false
        env:
          FLUTTER_ROOT: /opt/hostedtoolcache/flutter/stable-3.22.0-x64
          PUB_CACHE: /home/runner/.pub-cache

      - name: Run Microsoft Security DevOps
        uses: microsoft/security-devops-action@latest
        id: msdo

  build-web:
    runs-on: ubuntu-latest
    needs: [security]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
      - name: Install dependencies
        run: flutter pub get
      - name: Build Flutter project for web
        run: flutter build web --release
      - name: Upload web build
        uses: actions/upload-artifact@v3
        with:
          name: web-release
          path: build/web

      - name: Push changes to GitHub Pages
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
    
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}`

  approve-release:
    runs-on: ubuntu-latest
    needs: [security, build-web]
    environment:
      name: dev
      url: ${{ steps.msdo.outputs.url }}
    steps:
      - name: Request approval for release
        run: echo "Approval needed for release. Please approve the deployment in the 'dev' environment."

  build:
    runs-on: ubuntu-latest
    needs: [approve-release]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
      - name: Install dependencies
        run: flutter pub get
      - name: Build Flutter project
        run: flutter build apk --release
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
