name: Dart CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            packages/**/.packages
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.yaml') }}
      - name: Install dependencies
        run: flutter pub get
      - name: Prepare build directory
        run: flutter build apk --release
      - name: Save Flutter SDK and dependencies
        id: save_cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/build
            ${{ runner.tool_cache }}/flutter
          key: ${{ runner.os }}-flutter-sdk-${{ hashFiles('pubspec.yaml') }}

  format:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: Restore Flutter SDK and dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/build
            ${{ runner.tool_cache }}/flutter
          key: ${{ runner.os }}-flutter-sdk-${{ hashFiles('pubspec.yaml') }}
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

  analyze:
    runs-on: ubuntu-latest
    needs: format
    steps:
      - uses: actions/checkout@v4
      - name: Restore Flutter SDK and dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/build
            ${{ runner.tool_cache }}/flutter
          key: ${{ runner.os }}-flutter-sdk-${{ hashFiles('pubspec.yaml') }}
      - name: Analyze project source
        run: |
          flutter analyze || true
      - name: Output Analysis Results
        if: failure()
        run: exit 1

  test:
    runs-on: ubuntu-latest
    needs: analyze
    steps:
      - uses: actions/checkout@v4
      - name: Restore Flutter SDK and dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/build
            ${{ runner.tool_cache }}/flutter
          key: ${{ runner.os }}-flutter-sdk-${{ hashFiles('pubspec.yaml') }}
      - name: Run tests
        run: flutter test

  security:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Restore Flutter SDK and dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/build
            ${{ runner.tool_cache }}/flutter
          key: ${{ runner.os }}-flutter-sdk-${{ hashFiles('pubspec.yaml') }}
      - name: Check for vulnerabilities with Dart
        run: dart pub outdated --mode=null-safety
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.53.0
        with:
          image-ref: dart:stable
          severity: CRITICAL,HIGH

  build:
    runs-on: ubuntu-latest
    needs: security
    steps:
      - uses: actions/checkout@v4
      - name: Restore Flutter SDK and dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/build
            ${{ runner.tool_cache }}/flutter
          key: ${{ runner.os }}-flutter-sdk-${{ hashFiles('pubspec.yaml') }}
      - name: Build Flutter project
        run: flutter build apk --release
