name: Dart CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch: # Adiciona um gatilho manual para aprovação

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
      - name: Install dependencies
        run: flutter pub get
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze project source
        run: |
          flutter analyze || true
      - name: Output Analysis Results
        if: failure()
        run: exit 1

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
      - name: Install dependencies
        run: flutter pub get

      - name: Check for outdated dependencies with Dart
        run: dart pub outdated

      - name: Scan current project
        uses: anchore/scan-action@v3
        with:
          path: "."
          fail-build: false
          output-format: table
          severity-cutoff: medium
          only-fixed: false
          add-cpes-if-none: false
          by-cve: false
        env:
          FLUTTER_ROOT: /opt/hostedtoolcache/flutter/stable-3.22.0-x64
          PUB_CACHE: /home/runner/.pub-cache

      - name: Run Microsoft Security DevOps
        uses: microsoft/security-devops-action@latest
        id: msdo

  approve-release:
    runs-on: ubuntu-latest
    needs: [format, analyze, test, security]
    environment:
      name: dev
      url: ${{ steps.msdo.outputs.url }}
    steps:
      - name: Request approval for release
        run: echo "Approval needed for release. Please approve the deployment in the 'dev' environment."

  build:
    runs-on: ubuntu-latest
    needs: [approve-release]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
      - name: Install dependencies
        run: flutter pub get
      - name: Build Flutter project
        run: flutter build apk --release
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build-web:
    runs-on: ubuntu-latest
    needs: [format, analyze, test, security]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
      - name: Install dependencies
        run: flutter pub get
      - name: Build Flutter web project
        run: flutter build web --release --base-href "/freetogame/"
      - name: Upload Web
        uses: actions/upload-artifact@v3
        with:
          name: web-release
          path: build/web

  deploy:
    runs-on: ubuntu-latest
    needs: build-web
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download Web Artifact
        uses: actions/download-artifact@v3
        with:
          name: web-release
          path: build/web
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages
          allow_empty_commit: false
          keep_files: false
          force_orphan: false
          enable_jekyll: false
          disable_nojekyll: false
          exclude_assets: .github
